import Head from "next/head"
import Image from "next/image"

export default function Home() {
    return (
        <>
            <Head>
                <title>QR Code Component</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex items-center justify-center font-outfit bg-light-gray h-screen">
                <div className="bg-white rounded-3xl flex flex-col items-center justify-center p-4">
                    <div>
                        <Image
                            src="/image-qr-code.png"
                            alt="QR Code"
                            width={300}
                            height={300}
                            className="rounded-xl"
                        />
                    </div>
                    <div className="w-min py-6">
                        <h1 className="w-64 font-bold text-xl text-center text-dark-blue">
                            Improve your front-end skills by building projects
                        </h1>
                        <p className="text-center text-grayish-blue font-normal text-sm pt-4">
                            Scan the QR code to visit Frontend Mentor and take
                            your coding skills to the next level
                        </p>
                    </div>
                </div>
            </main>
        </>
    )
}
